export interface Producto{
  id             : number,
  dispositivo_ID : number,
  marca_ID       : number,
  modelo_ID      : number,
  nombre_producto: string,
  precio         : number,
  cantidad       : number,
  descripcion    : string,
  aplica_puntos  : boolean,
  cantidad_puntos: number,
  en_oferta      : boolean,
  descuento       : number,
  caducidad_puntos: Date,
  caducidad_oferta: Date,
  envio_gratis    : boolean,
  evento_ID       : number,
  presentacion_Producto_ID: number,
  tipo_producto_ID : number,
  es_elimidado     : boolean
}